"""Add AuthKV table

Revision ID: 37aeecea6151
Revises: 
Create Date: 2023-01-05 11:48:26.493810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37aeecea6151'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_kv',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_kv')
    # ### end Alembic commands ###
